# File: Project3.py
# Student: Jingsi Zhou
# UT EID: jz24729
# Course Name: CS303E
# Unique Number: 50695
# 
# Date Created: 12/04/2020
# Date Last Modified: 12/04/2020    
# Description of Program: This program utilizes turtle graphics and draws a simple rendering of the UT Tower
# in color. I added comic sans font because it was late at night and I wanted to make myself laugh...

import turtle
import math
from PIL import Image

def DrawStairs(t):
    t.pencolor("#d1d1d1")
    t.fillcolor("#d1d1d1")
    t.begin_fill()
    t.forward(300)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(300)
    t.left(90)
    t.forward(10)
    t.penup()
    t.goto(10, 12)
    t.pendown()
    t.right(270)
    t.forward(280)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(280)
    t.left(90)
    t.forward(10)
    t.penup()
    t.goto(20, 24)
    t.pendown()
    t.right(270)
    t.forward(260)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(260)
    t.left(90)
    t.forward(10)
    t.penup()
    t.goto(30, 36)
    t.pendown()
    t.right(270)
    t.forward(240)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(240)
    t.left(90)
    t.forward(10)
    t.end_fill()
    t.penup()

def DrawBuilding(t):
    t.goto(30, 48)
    t.pendown()
    t.pencolor("#d1d1d1")
    t.fillcolor("#d1d1d1")
    t.begin_fill()
    t.right(180)
    t.forward(60)
    t.right(90)
    t.forward(240)
    t.right(90)
    t.forward(60)
    t.right(90)
    count = 0
    while count < 9:
        t.forward(6)
        t.right(90)
        t.forward(30)
        t.circle(10, 180)
        t.forward(30)
        t.right(90)
        count += 1
    t.end_fill()
    t.penup()
    t.goto(30, 110)
    t.pendown()
    t.pencolor("#d45c00")
    t.fillcolor("#d45c00")
    t.begin_fill()
    t.right(180)
    t.forward(240)
    t.left(135)
    t.forward(math.sqrt(2)*30)
    t.left(45)
    t.forward(180)
    t.left(45)
    t.forward(math.sqrt(2)*30)
    t.end_fill()
    t.penup()

def DrawTower(t):
    t.goto(124, 142)
    t.pendown()
    t.pencolor("#eb8900")
    t.fillcolor("#eb8900")
    t.begin_fill()
    t.right(135)
    t.forward(120)
    t.left(90)
    t.forward(2)
    t.right(90)
    t.forward(8)
    t.right(90)
    t.forward(2)
    t.left(90)
    t.forward(3)
    t.right(90)
    t.forward(3)
    t.left(90)
    t.forward(9)
    t.right(90)
    t.forward(6)
    t.left(90)
    t.forward(32)
    t.left(90)
    t.forward(2)
    t.right(90)
    t.forward(4)
    t.right(90)
    t.forward(3)
    t.left(90)
    t.forward(4)
    t.right(90)
    t.forward(32)  # top
    t.right(90)
    t.forward(4)
    t.left(90)
    t.forward(3)
    t.right(90)
    t.forward(4)
    t.right(90)
    t.forward(2)
    t.left(90)
    t.forward(32)
    t.left(90)
    t.forward(6)
    t.right(90)
    t.forward(9)
    t.left(90)
    t.forward(3)
    t.right(90)
    t.forward(3)
    t.left(90)
    t.forward(2)
    t.right(90)
    t.forward(8)
    t.right(90)
    t.forward(2)
    t.left(90)
    t.forward(120)
    t.right(90)
    t.forward(52)
    t.end_fill()
    t.penup()
    
def DrawCircle(t):
    t.goto(150, 279)
    t.pendown()
    t.pencolor("#ffffff")
    t.fillcolor("#ffffff")
    t.begin_fill()
    t.circle(4, 360)
    t.end_fill()
    t.penup()
    
def DrawBars(t):
    t.goto(161, 286)
    t.pendown()
    t.pencolor("#ffffff")
    t.fillcolor("#ffffff")
    t.begin_fill()
    t.right(180)
    t.forward(2)
    t.left(90)
    t.forward(24)
    t.left(90)
    t.forward(2)
    t.left(90)
    t.forward(24)
    t.penup()
    t.goto(137, 286)
    t.pendown()
    t.left(90)
    t.forward(2)
    t.left(90)
    t.forward(24)
    t.left(90)
    t.forward(2)
    t.left(90)
    t.forward(24)
    t.end_fill()
    t.up()
    
def Windows(t):
   t.goto(136, 144)
   t.left(90)
   t.down()
   rows = 0
   NUMPERROW = 3
   x = 136
   y = 144
   while rows < 11:
        for i in range(NUMPERROW):
            t.pencolor("#ffffff")
            t.fillcolor("#ffffff")
            t.begin_fill()
            t.forward(4)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.forward(4)
            t.left(90)
            t.forward(7)
            t.left(90)
            t.penup()
            x += 12
            t.setx(x)
            t.pendown()
            t.end_fill()
        t.penup()
        x = 136
        t.setx(x)
        y += 10.9
        t.sety(y)
        t.pendown()
        rows += 1
   t.penup()

def HookEm(t):
    t.goto(150, -34)
    t.pencolor("#eb8900")
    t.pendown()
    t.write("Hook 'em!", align = "center", font = ('Comic Sans MS', 20, "bold"))
    
poo = turtle.Turtle()	
poo.speed(10)
DrawStairs(poo)
DrawBuilding(poo)
DrawTower(poo)
DrawCircle(poo)
DrawBars(poo)
Windows(poo)
HookEm(poo)
poo.hideturtle()
turtle.done()

